# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Express sample

on:
  push:
    branches: [ "main" ]
    paths:
      - "ams-express-shopping/**"
      - ".github/workflows/build_and_test_expressjs.yml"
  pull_request:
    branches: [ "**" ]
    paths:
      - "ams-express-shopping/**"
      - ".github/workflows/build_and_test_expressjs.yml"

jobs:
  npm:
    runs-on: [ ubuntu-latest, solinas ]
    env:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk
    strategy:
      matrix:
        node-version: [20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ams-express-shopping
    - name: Set up JDK 17 # for DCL -> DCN compilation to work before tests
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: npm ci
      working-directory: ams-express-shopping
    - run: npm test
      working-directory: ams-express-shopping